- hosts: aws_instance
  vars:
    username: pass_your_username_here
  remote_user: "{{username}}"
  become: yes
  become_method: sudo
  tasks:
    - name: Copy airbnb_dl_model directory 
      copy:
        src: airbnb_dl_model
        dest: "/home/{{username}}"
    
    - name: Copy Dockerfile 
      copy:
        src: Dockerfile
        dest: "/home/{{username}}"
        directory_mode: yes
    
    - name: Build Docker image from Dockerfile
      command: "docker build -t airbnb_dl /home/{{username}}/"
        
    - name: Running the container
      command: "docker run -v /home/{{username}}/airbnb_dl_model:/etc/airbnb_dl_model airbnb_dl"